workflows:
  flutter-app:
    name: my3iL
    working_directory: frontend/app_student
    environment:
      flutter: "3.19.2"
      xcode: latest
      vars:
        PROD_API_URL: "https://api.lukasvalois.com"
        DEV_API_URL: "https://api-dev.lukasvalois.com"
      groups:
        - firebase_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: dev
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Add Firebase configuration
        script: |
          echo $FIREBASE_CONFIG | base64 --decode > android/app/google-services.json
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - lukas.valois@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true