workflows:
  flutter-app:
    name: my3iL
    working_directory: frontend/app_student
    environment:
      flutter: "3.19.2"
      xcode: latest
      vars:
        PROD_API_URL: "https://api.lukasvalois.com"
        DEV_API_URL: "https://api-dev.lukasvalois.com"
        PROJECT_ROOT: "$CM_BUILD_DIR/frontend/app_student"
      android_signing:
        - GooglePlayLukas
      groups:
        - firebase_things
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: dev
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$PROJECT_ROOT/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Add Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e # exit on first failed command
          echo $ANDROID_FIREBASE_SECRET > $PROJECT_ROOT/android/app/google-services.json
      - name: Build AAB with Flutter
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - lukas.valois@gmail.com
        notify:
          success: true
          failure: true