// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2r1gdCjzMbrL4AMO0SqHjmHnhlvNwmk',
    appId: '1:611754403427:web:c9fe5b77f2e2e71be9ba56',
    messagingSenderId: '611754403427',
    projectId: 'my3il-c3afd',
    authDomain: 'my3il-c3afd.firebaseapp.com',
    storageBucket: 'my3il-c3afd.appspot.com',
    measurementId: 'G-LXGMW8L06H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSr9ykg41ld5ahkKeT5rpGS8eoeFn72WU',
    appId: '1:611754403427:android:b4ebb05b784f5da7e9ba56',
    messagingSenderId: '611754403427',
    projectId: 'my3il-c3afd',
    storageBucket: 'my3il-c3afd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwItNhczaC0NQ6BJmUFS87kduyzelhoDA',
    appId: '1:611754403427:ios:b9dbe000cab01ab2e9ba56',
    messagingSenderId: '611754403427',
    projectId: 'my3il-c3afd',
    storageBucket: 'my3il-c3afd.appspot.com',
    iosBundleId: 'fr.my3il.appstudent',
  );
}
