name: Execute Lint and Format

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  FLUTTER_VERSION: 3.19.2

jobs:
  format-lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: ":os:-modules-:hash:"
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install dependencies
        run: |
          cd frontend/app_student
          flutter pub get

      - name: Formatting
        run: dart --disable-analytics format --set-exit-if-changed frontend/app_student/lib

      - name: Lint
        run: flutter analyze frontend/app_student/lib